### ISSUE TITLE
Add support for setting Cache-Control Immutable

### ISSUE THREAD

**Issue by Eilon** [aspnet/ResponseCaching#98] opened 2017-01-30 18:07 UTC
See https://github.com/aspnet/HttpAbstractions/issues/763.

Should make sure that a developer can set this for a request.

**Comment by Tratcher** [comment] 2017-01-30 18:09
Duplicate of https://github.com/aspnet/ResponseCaching/issues/97

**Closed by Tratcher** 2017-01-30 18:09 UTC
