### ISSUE TITLE
Users are able to make site throw an exception when using ResponseCaching middleware.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/ResponseCaching#85] opened 2016-12-08 07:51 UTC
using the `ResponseCachingMiddleware` with `VaryByQueryKeys`

```
[ResponseCache(CacheProfileName = "DefaultCache", VaryByQueryKeys = new string[] { "id" })]
```

open chrome inspector
tick disable cache
go to page that uses a `ResponseCache` with `VaryByQueryKeys` 

![image](https://cloud.githubusercontent.com/assets/3386797/21001439/1c2d671e-bcff-11e6-9de2-7bd5518a9327.png)

it throws: 
InvalidOperationException: 'VaryByQueryKeys' requires the response cache middleware.

closing the inspector or untick disable cache work fine.

Using fiddler, adding `Pragma: no-cache` header is enough to make the site throw an exception.

**Comment by GuardRex** [comment] 2016-12-08 07:52
Confirmed here.

![capture](https://cloud.githubusercontent.com/assets/1622880/21001985/f6d371c2-bce8-11e6-9bb4-bbec46d5b986.PNG)

**Comment by ctolkien** [comment] 2016-12-08 08:00
We're hitting this issue in production - as reported by App Insights:

![image](https://cloud.githubusercontent.com/assets/515955/21002176/89c9698e-bd78-11e6-9989-9a00eb33d25b.png)

**Comment by Bartmax** [comment] 2016-12-08 08:12
Looks like incognito mode on safari render the actions with `VaryByQueryKeys` useless too.

**Comment by Bartmax** [comment] 2016-12-08 08:24
dupe of https://github.com/aspnet/ResponseCaching/issues/81

**Comment by JunTaoLuo** [comment] 2016-12-09 23:59
Yes this is a duplicate of #81

**Closed by JunTaoLuo** 2016-12-09 23:59 UTC
Labels: duplicate
